# Generated by Django 4.2.2 on 2023-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_perscription_number_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
