# Generated by Django 4.2.2 on 2023-07-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perscription',
            name='medicine',
        ),
        migrations.CreateModel(
            name='PerscriptionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicine')),
                ('perscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perscription')),
            ],
        ),
    ]
