# Generated by Django 4.2.2 on 2023-07-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_perscription_medicine_perscriptionitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perscription',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
