# Generated by Django 4.2.2 on 2023-07-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_perscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perscription',
            name='number',
        ),
        migrations.AlterField(
            model_name='perscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
