# Generated by Django 4.2.2 on 2023-07-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_perscription_number_alter_perscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
