# Generated by Django 4.2.2 on 2023-07-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
